apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
      - job_name: "orderer10"
        static_configs: 
          - targets: ["orderer1-org0-com:30850"]
      - job_name: "orderer20"
        static_configs: 
          - targets: ["orderer2-org0-com:30860"]
      - job_name: "peer_org1"
        static_configs: 
          - targets: ["peer1-org1-com:30851"]
      - job_name: "peer_org2"
        static_configs: 
          - targets: ["peer1-org2-com:30856"]

#       - job_name: kubernetes
      #   kubernetes_sd_configs:
      #   - api_server: 'https://kubernetes'
      #     role: pod
      #     tls_config:
      #       ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      #     bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      #   relabel_configs:
      #   - source_labels:
      #     - __meta_kubernetes_pod_name
      #     target_label: container_label_io_kubernetes_pod_name
      #   - source_labels:
      #     - __meta_kubernetes_namespace
      #     target_label: container_label_io_kubernetes_pod_namespace
      #   - source_labels:
      #     - __meta_kubernetes_pod_container_port_number
      #     target_label: container_label_port
#        - source_labels:
#          - container_label_io_kubernetes_pod_name
#          target_label: exported_container_label_io_kubernetes_pod_name
#        - source_labels:
#          - container_label_io_kubernetes_pod_namespace
#          target_label: exported_container_label_io_kubernetes_pod_namespace
