Organizations:
    - &org0
        Name: org0
        ID: org0
        MSPDir: ../ordererOrgs/org0/msp
        
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('org0.admin', 'org0.peer', 'org0.client')"
            Writers:
                Type: Signature
                Rule: "OR('org0.admin', 'org0.client', 'org0.orderer')"
            Admins:
                Type: Signature
                Rule: "OR('org0.admin')"

    - &org1
            Name: org1
            ID: org1
            MSPDir: ../peerOrgs/org1/msp
            
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('org1.admin', 'org1.peer', 'org1.client')"
                Writers:
                    Type: Signature
                    Rule: "OR('org1.admin', 'org1.client')"
                Admins:
                    Type: Signature
                    Rule: "OR('org1.admin')"
                Endorsement:
                    Type: Signature
                    Rule: "OR('org1.peer')"

            OrdererEndpoints:
                - "orderer1-org0-com:30750"                            
                - "orderer2-org0-com:30760"
                                    
            AnchorPeers:
                - Host: peer1-org1-com
                  Port: 30751

    - &org2
            Name: org2
            ID: org2
            MSPDir: ../peerOrgs/org2/msp
            
            Policies:
                Readers:
                    Type: Signature
                    Rule: "OR('org2.admin', 'org2.peer', 'org2.client')"
                Writers:
                    Type: Signature
                    Rule: "OR('org2.admin', 'org2.client')" 
                Admins:
                    Type: Signature
                    Rule: "OR('org2.admin')"
                Endorsement:
                    Type: Signature
                    Rule: "OR('org2.peer')" 
                    
            OrdererEndpoints:
                - "orderer1-org0-com:30750"                            
                - "orderer2-org0-com:30760"
                    
            AnchorPeers:
                - Host: peer1-org2-com
                  Port: 30756
                    
                    
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true
        
        
Application: &ApplicationDefaults
    #policies that govern how peer organizations can interact with application channels 
    #(e.g.: number of peer for approval of a chaincode definition, 
    #   restict access to channel resources: ability to write to the channel ledger or query channel events)
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"           
    Capabilities:
        <<: *ApplicationCapabilities
        
        
Orderer: &OrdererDefaults
    OrdererType: etcdraft   #type of consensus
    EtcdRaft:
        #consenter set: ordering nodes actively participating in the consensus mechanism on a channel
        #   with the ability to create new blocks and distribute them to the peers joined to the channel
        Consenters:
        - Host: orderer1-org0-com
          Port: 30750
          ClientTLSCert: ../ordererOrgs/org0/orderer1/tls/signcerts/cert.pem
          ServerTLSCert: ../ordererOrgs/org0/orderer1/tls/signcerts/cert.pem
        - Host: orderer2-org0-com
          Port: 30760
          ClientTLSCert: ../ordererOrgs/org0/orderer2/tls/signcerts/cert.pem
          ServerTLSCert: ../ordererOrgs/org0/orderer2/tls/signcerts/cert.pem
          
    #A block will be cut when any of the BatchTimeout or BatchSize criteria has been met.
    BatchTimeout: 2s   
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 49 MB
        PreferredMaxBytes: 512 KB
        
    Organizations:
    Policies:
        #policies that govern the channel consenter set
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
            
            
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities
        

#The configtxgen tool 
# -reads the channel profiles in the Profiles section  
# -builds a channel configuration
# -uses this configuration to create a channel creation transaction for an applications channel
Profiles:
    #A consortium is a collection of non-orderer organizations on the blockchain network. These are the organizations that form and join channels and that own peers. 
    default:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults    #uses the default policies from the Application section to govern how peer organizations will interact with the channel
            Organizations:
                - *org1
                - *org2
            Capabilities:
                <<: *ApplicationCapabilities
    
    #The system channel is used by the ordering service as a template to create application channels
    genesis:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            Addresses:
                - orderer1-org0-com:30750
                - orderer2-org0-com:30760
            Organizations:
                - *org0
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
            - <<: *org1
            - <<: *org2
        Consortiums:
            SampleConsortium:
                Organizations:
                - *org1
                - *org2